config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  mount UserApi::Base, at: '/api'
  mount ManagementAPI::V1::Base, at: '/management_api'

  devise_for :accounts, controllers: { sessions: :sessions,
                                       confirmations: :confirmations }
  devise_scope :account do
    match 'accounts/sign_in/confirm', to: 'sessions#confirm', via: %i[get post]
  end

  root to: 'index#index', as: :index

  post 'phones/verification', to: 'phones#verify'

  get  'security',            to: 'security#enable'
  post 'security/confirm',    to: 'security#confirm'

  resources :phones,    only: %i[new create]
  resources :profiles,  only: %i[new create]
  resources :documents, only: %i[new create]

  namespace :admin do
    get '/', to: 'accounts#index', as: :accounts
    resources :accounts, except: %i[new create] do
      resources :labels, except: %i[index show]
    end
    resources :websites
    resources :profiles, only: %i[edit update] do
      put :document_label, on: :member
    end
  end
end

app/models/account.rb
# frozen_string_literal: true

#
# Class Account
#
class Account < ApplicationRecord
  include Discard::Model
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable,
         :confirmable, :lockable

  ROLES = %w[admin compliance member].freeze

  acts_as_eventable prefix: 'account', on: %i[create update]

  has_one :profile, dependent: :destroy
  has_many :phones, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :labels
  has_many :api_keys, class_name: 'APIKey'

  before_validation :assign_uid

  validates :email, email: true
  validates :email, uniqueness: true
  validates :uid, presence: true, uniqueness: true

  def active_for_authentication?
    super && !discarded_at
  end

  def role
    super.inquiry
  end

  def after_confirmation
    add_level_label(:email)
    self.state = 'active'
    save
  end

  def update_level
    tags = []
    account_level = 0
    tags = labels.with_private_scope
                 .map { |l| [l.key, l.value].join ':' }
    levels = Level.all.order(id: :asc)

    levels.each do |lvl|
      break unless tags.include?(lvl.key + ':' + lvl.value)
      account_level = lvl.id
    end

    update(level: account_level)
  end

  def add_level_label(key, value = 'verified')
    labels.find_or_create_by(key: key, scope: 'private')
          .update!(value: value)
  end

  def assign_uid
    return unless uid.blank?
    loop do
      self.uid = random_uid
      break unless Account.where(uid: uid).any?
    end
  end

  def random_uid
    "ID#{SecureRandom.hex(5).upcase}"
  end

  def as_json_for_event_api
    {
      uid: uid,
      email: email,
      level: level,
      otp_enabled: otp_enabled,
      confirmation_token: confirmation_token,
      confirmed_at: format_iso8601_time(confirmed_at),
      confirmation_sent_at: format_iso8601_time(confirmation_sent_at),
      reset_password_token: reset_password_token,
      reset_password_sent_at: format_iso8601_time(reset_password_sent_at),
      state: state,
      failed_attempts: failed_attempts,
      unlock_token: unlock_token,
      locked_at: locked_at,
      created_at: format_iso8601_time(created_at),
      updated_at: format_iso8601_time(updated_at)
    }
  end
end

# == Schema Information
# Schema version: 20180508095253
#
# Table name: accounts
#
#  id                     :integer          not null, primary key
#  uid                    :string(255)      not null
#  email                  :string(255)      not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  role                   :string(255)      default("member"), not null
#  level                  :integer          default(0), not null
#  otp_enabled            :boolean          default(FALSE)
#  state                  :string(255)      default("pending"), not null
#  discarded_at           :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_accounts_on_confirmation_token    (confirmation_token) UNIQUE
#  index_accounts_on_discarded_at          (discarded_at)
#  index_accounts_on_email                 (email) UNIQUE
#  index_accounts_on_reset_password_token  (reset_password_token) UNIQUE
#  index_accounts_on_uid                   (uid) UNIQUE
#  index_accounts_on_unlock_token          (unlock_token) UNIQUE
#

app/controllers/admin/accounts_controller.rb
# frozen_string_literal: true

module Admin
  class AccountsController < ModuleController
    before_action :find_account, except: :index

    def index
      @accounts = Account.kept.page(params[:page])
    end

    def show
      @profile = @account.profile
      @documents = @account.documents
      @labels = @account.labels
      @phones = @account.phones
      @document_label_value = document_label&.value
    end

    def edit
    end

    def update
      @account.update!(account_params)
      redirect_to admin_accounts_url
    end

    def destroy
      @account.discard
      respond_to do |format|
        format.html { redirect_to admin_accounts_url, notice: 'Account is marked as discarded' }
      end
    end

  private

    def find_account
      @account = Account.kept.find(params[:id])
    end

    def document_label
      @account.labels.find_by(key: 'document', scope: 'private')
    end

    def account_params
      params.require(:account).permit(:role)
    end
  end
end

app/views/admin/accounts/_document_label.html.erb
<li class="list-group-item">
  <b> Document: </b>
  <div class="dropdown show">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= @document_label_value %>
    </a>
    <div class="dropdown-menu">
      <% Document::STATES.each do |state|%>
        <%=
          unless @document_label_value == state
            link_to(state.upcase_first,
                    document_label_admin_profile_path(@account.profile, state: state), method: :put,
                                                                                       class: 'dropdown-item')
          end
        %>
     <% end %>
    </div>
  </div>
</li>

app/views/admin/accounts/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit account</h1>
  </div>
  <%= form_for([:admin, @account], method: :put) do |f| %>
    <div class="form-group">
      <%= f.label :role, class: 'control-label' %><br />
      <%= f.select :role, Account::ROLES, {}, class: 'form-control col-sm-2' %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), admin_accounts_path,  class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/admin/accounts/index.html.erb
<div class="container">

  <h1>Accounts</h1>

  <table class="table table-bordered table-striped table-hover table-sm text-center">
    <thead>
      <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Role</th>
        <th>Level</th>
        <th>Labels</th>
        <th>Last sign in</th>
        <% if can?(:update, Account) || can?(:destroy, Account) %>
          <th colspan=3></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
        <tr class=<%= 'table-danger' if account.unlock_token? %>>
          <td><%= account.id %></td>
          <td><%= link_to account.email, admin_account_path(account.id) %></td>
          <td><span class=" badge <%= badge_by_role(account.role) %>"> <%= account.role %> </span></td>
          <td><%= account.level %></td>
          <td><%= label_tags(account) %></td>
          <td><%= account.last_sign_in_at.to_s(:long) if account.last_sign_in_at? %></td>
          <% if can? :update, account %>
            <td><%= link_to 'Edit', edit_admin_account_path(account.id),  class: 'btn btn-primary btn-sm'  %></td>
          <% end %>

          <% if can? :destroy, account %>
            <td><%= link_to 'Delete', admin_account_path(account.id), method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: 'Are you sure?'} %></td>
          <% end %>

          </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @accounts %>
</div>

app/views/admin/accounts/show.html.erb
<div class="container">
  <h4 class="text-center">Account</h4>
  <ul class="list-group">
    <li class="list-group-item">
     <b> E-mail: </b>
      <%= @account.email%>
    </li >

    <li class="list-group-item">
     <b> Role: </b>
      <%= @account.role %>
    </li >

    <li class="list-group-item">
     <b> Level: </b>
      <%= @account.level %>
    </li >

    <li class="list-group-item">
     <b> 2FA enabled?: </b>
      <%= @account.otp_enabled %>
    </li >
  </ul>
  <br/>
  
</br/>

  <h4 class="text-center"> Profile </h4>
  <ul class="list-group">
    <% if @profile %>
      <li class="list-group-item">
        <b> First Name: </b>
        <%= @profile.first_name%>
      </li>

      <li class="list-group-item">
        <b> Last Name: </b>
        <%= @profile.last_name%>
      </li>

      <li class="list-group-item">
        <b> Address: </b>
        <%= @profile.address%>
      </li>

      <li class="list-group-item">
        <b> Postcode: </b>
        <%= @profile.postcode%>
      </li>

      <li class="list-group-item">
        <b> City: </b>
        <%= @profile.city%>
      </li>

      <li class="list-group-item">
        <b> Country: </b>
        <%= @profile.country%>
      </li>

      <% if @document_label_value %>
        <%= render 'document_label' %>
      <% end %>
      <li class="list-group-item">
        <% if can? :update, Profile %>
          <%= link_to 'Edit', edit_admin_profile_path(@account.profile), class: 'btn btn-primary btn-sm' %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <br>
  <h4 class="text-center"> Phones </h4>
  <table class="table table-bordered table-striped table-hover table-sm text-center">
    <thead>
    <tr>
      <th>ID</th>
      <th>Country</th>
      <th>Number</th>
      <th>Vlidated at</th>
    </tr>
    </thead>
    <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.id %></td>
        <td><%= phone.country %></td>
        <td><%= phone.number %></td>
        <td><%= phone.validated_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <h4 class="text-center"> Documents </h4>
  <table class="table table-bordered table-striped table-hover table-sm text-center">
    <thead>
    <tr>
      <th>ID</th>
      <th>Doc Photo</th>
      <th>Doc Name</th>
      <th>Doc Type</th>
      <th>Doc Number</th>
      <th>Doc Expire</th>
    </tr>
    </thead>
    <tbody>
    <% @documents.each do |document| %>
        <tr>
          <td><%= document.id %></td>
          <td><%= document.upload.present? ? link_to(image_tag(document.upload.url, width: '100', alt: 'Doc Preview'), asset_path(document.upload), target: '_blank') : ''%></td>
          <td><%= document.upload&.file&.filename%></td>
          <td><%= document.doc_type %></td>
          <td><%= document.doc_number %></td>
          <td><%= document.doc_expire %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <% if can? :create, Label %>
    <%= link_to 'New Label', new_admin_account_label_path(@account.id), class: 'btn btn-success' %>
  <% end %>
  <br>
  <h4 class="text-center"> Labels </h4>
  <table class="table table-bordered table-striped table-hover table-sm text-center">
    <thead>
    <tr>
      <th>ID</th>
      <th>Key</th>
      <th>Value</th>
      <th>Scope</th>
    </tr>
    </thead>
    <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.id %></td>
        <td><%= label.key %></td>
        <td><%= label.value %></td>
        <td><%= label.scope %></td>
        <td>
          <% if can? :update, Label %>
            <%= link_to 'Edit', edit_admin_account_label_path(id: label.id, account_id: @account.id), class: 'btn btn-primary btn-sm' %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, Label %>
            <%= link_to 'Delete', admin_account_label_path(id: label.id, account_id: @account.id), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>