config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  mount UserApi::Base, at: '/api'
  mount ManagementAPI::V1::Base, at: '/management_api'

  devise_for :accounts, controllers: { sessions: :sessions,
                                       confirmations: :confirmations }
  devise_scope :account do
    match 'accounts/sign_in/confirm', to: 'sessions#confirm', via: %i[get post]
  end

  root to: 'index#index', as: :index

  post 'phones/verification', to: 'phones#verify'

  get  'security',            to: 'security#enable'
  post 'security/confirm',    to: 'security#confirm'

  resources :phones,    only: %i[new create]
  resources :profiles,  only: %i[new create]
  resources :documents, only: %i[new create]

  namespace :admin do
    get '/', to: 'accounts#index', as: :accounts
    resources :accounts, except: %i[new create] do
      resources :labels, except: %i[index show]
    end
    resources :websites
    resources :profiles, only: %i[edit update] do
      put :document_label, on: :member
    end
  end
end

app/views/layouts/shared/_account_footer.html.erb
<div class="card-footer py-3 px-5">
  <div class="row">
    <div class="col text-left">
      <div class="btn-group">
        <a href="javascript:void(0)" class="dropdown-toggle text-white" data-toggle="dropdown">
          Settings
        </a>
        <div class="dropdown-menu text-dark">
          <%= link_to "Change your password", edit_account_registration_path, class:'dropdown-item' %>

          <% if Vault::TOTP.server_available? && !current_account.otp_enabled %>
            <%= link_to 'Enable two factor authentification', security_path, class:'dropdown-item' %>
          <% end %>

          <%= link_to 'Upload document', new_document_path, class:'dropdown-item' if current_account.profile %>
          <%= link_to 'Add phone', new_phone_path, class:'dropdown-item' %>
        </div>
      </div>

    </div>
    <div class="col text-right">
      <%= link_to 'Sign out', destroy_account_session_path, method: :get, class: "text-white" %>
    </div>
  </div>
</div>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark mb-4">
  <div class="container">
    <%= link_to 'Barong', index_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if params[:controller].match?(/phones/) %>">
          <%= link_to 'Phone', new_phone_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if params[:controller].match?(/profiles/) %>">
          <%= link_to 'Profile', new_profile_path, class: 'nav-link' %>
        </li>
      </ul>
      <%= link_to 'Sign out', destroy_account_session_path, method: :get %>
    </div>
  </div>
</nav>